controllers/OrderController.php
<?php

namespace app\controllers;

use Yii;
use PhpOffice\PhpSpreadsheet\Spreadsheet;
use yii\filters\AccessControl;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;
use app\models\form\UpdateDictForm;
use app\models\general\Order;
use app\models\general\OrderSearch;
use app\models\dict\MaterialType;
use app\models\dict\Operation;
use app\models\dict\Color;
use app\models\dict\SecondaryMaterial;
use app\models\User;
use app\models\general\OrderOperation;
use app\models\general\OrderOperationSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use DateTime;

/**
 * OrderController implements the CRUD actions for Order model.
 */
class OrderController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
            'access' => [
                'class' => AccessControl::className(),
                
                'rules' => [
                    [
                    'actions' => ['index','view','update','create','delete'],
                    'allow' => true,
                    'roles' => ['@'],
                    ],

                ],
            ],
        ];
    }

    /**
     * Lists all Order models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new OrderSearch();
        $update_form = new UpdateDictForm();

        $dataProvider = $searchModel->search(Yii::$app->request->queryParams, Yii::$app->user->identity->role);


        $directory = realpath(dirname(__FILE__).'/../files/orders/');
        $scanned_directory = array_slice(scandir($directory), 2);

        if ($update_form->load(Yii::$app->request->post()) && $update_form->validate()) 
        {
            foreach ($scanned_directory as  $kkk=> $sd) {
                $reader = new \PhpOffice\PhpSpreadsheet\Reader\Xlsx();
                $reader->setReadDataOnly(true);
                $spreadsheet = $reader->load($directory.'/'.$sd);
                $worksheet = $spreadsheet->getActiveSheet();
                $rows = $worksheet->toArray();
                // print_r('<pre>');
                // print_r($rows);
                // print_r('</pre>');
                // die;
                $order_general_id = $rows[3][1];

                $order_gl_ids = explode(' ', $order_general_id);
                $order_local_id_value = '';
                $order_general_id_value = '';
                foreach ($order_gl_ids as $key => $order_gl_id) {
                    if ($key == 0) {
                        $order_local_id_value = $order_gl_id;
                    } else {
                        $order_general_id_value .= $order_gl_id . ' ';
                    }
                }
                $order_general_id_value = substr($order_general_id_value, 0, -1);
                //проверяем если в базе такой номер заказа
                $check_order = Order::find()->where(['order_local_id' => $order_local_id_value])->one();

                //если заказа нет, то добавляем
                if(!$check_order)
                {

                    $order = new Order();

                    $order->order_general_id = $order_general_id_value;
                    $order->order_local_id = $order_local_id_value;
                    

                    $date = new DateTime();
                    $date->modify('+1 hour');
                    $order->date_in = $date->format('Y-m-d');
                    $date_out = $date->modify('+21 day');
                    $order->date_out = $date_out->format('Y-m-d');
                    //
                   
                    $order->user_id = Yii::$app->user->getId();
                    $order->save();
                    
                    $check_order = Order::find()->where(['order_local_id' => $order_local_id_value])->asArray()->one();

                }

                
                $order_id = $check_order['order_id'];
                
              
                $status = false;

                $last_row = end($rows);
                foreach ($rows as $key => $row) {

                    if($key > 10)
                    {

                        if($status)
                        {   
                            
                            $check_order_operation = OrderOperation::find()->where(['material_type_id' => $order_operation->material_type_id])->andWhere(['operation_id' => $order_operation->operation_id])->andWhere(['order_id' => $order_operation->order_id])->one();

                            if(!$check_order_operation)
                            {
                                

                                $order_operation->save();


                            } else
                            {
                                
                                $check_order_operation->cost = $order_operation->cost;
                                $check_order_operation->save();
                            }
                            $status = false;
                        }

                        //если нашли тип материала
                        if($row[0] && !$row[1])
                        {
                            $material_type = MaterialType::find()->where(['name' =>$row[0]])->asArray()->one();
                            if ($material_type)
                            {
                                $material_type = $material_type['material_type_id'];
                                

                            } else {}
                        }

                        //если нашли операцию
                        if($row[1])
                        {
                            $operation = Operation::find()->where(['name'=>$row[0]])->asArray()->one();
                            if($operation)
                            {
                                $order_operation = new OrderOperation();

                                $order_operation->material_type_id = $material_type;
                                $order_operation->order_id = $order_id;
                                $order_operation->operation_id = $operation['operation_id'];
                                $order_operation->cost = round($operation['value']*$row[2],2);
                                $status = true;

                            }
 
                        }
                        if($last_row[0] == $row[0] && $last_row[1] == $row[1] && $last_row[2] == $row[2])
                        {
                             $check_order_operation = OrderOperation::find()->where(['material_type_id' => $order_operation->material_type_id])->andWhere(['operation_id' => $order_operation->operation_id])->andWhere(['order_id' => $order_operation->order_id])->one();

                            if(!$check_order_operation)
                            {
                                $order_operation->save();

                            } else
                            {
                                $check_order_operation->cost = $order_operation->cost;
                                $check_order_operation->save();
                            }
                            $status = false;
                        }


                    }

                }
               


                
            }


        }

        return $this->render('index', [
            'searchModel' => $searchModel,
            'update_form' => $update_form,
            'dataProvider' => $dataProvider,
        ]);
    }


    public function actionUpd()
    {
        $orders = Order::find()->all();
        foreach ($orders as $order) {
            $order_general_id = $order->order_general_id;

            $order_gl_ids = explode(' ', $order_general_id);
            $order_local_id_value = '';
            $order_general_id_value = '';
            foreach ($order_gl_ids as $key => $order_gl_id) {
                if ($key == 0) {
                    $order_local_id_value = $order_gl_id;
                } else {
                    $order_general_id_value .= $order_gl_id . ' ';
                }
            }
            $order_general_id_value = substr($order_general_id_value, 0, -1);


            $order->order_general_id = $order_general_id_value;
            $order->order_local_id = $order_local_id_value;
            $order->save();
        }
    }

    /**
     * Displays a single Order model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        $final_order_operations = array();
        $order_operations = OrderOperation::find()->where(['order_id' => $id])->all();
        foreach ($order_operations as $order_operation) {
            $material_type = MaterialType::find()->where(['material_type_id' => $order_operation->material_type_id])->one();
            if ($material_type) { 
                $material_type_name = $material_type->name;
            } else {
                $material_type_name = '';
            }
            $operation = Operation::find()->where(['operation_id' => $order_operation->operation_id])->one();
            $user_data = User::find()->where(['user_id' => $order_operation->user_id])->one();
            if ($user_data) {
                $user_data_name = $user_data->lastname . ' ' . $user_data->firstname . ' ' . $user_data->patronymic;
            } else {
                $user_data_name = '';
            }
            $user_2_data = User::find()->where(['user_id' => $order_operation->user_id_2])->one();
            if ($user_2_data) {
                $user_2_data_name = $user_2_data->lastname . ' ' . $user_2_data->firstname . ' ' . $user_2_data->patronymic ;
            } else {
                $user_2_data_name = '';
            }

controllers/OrderOperationController.php
<?php

namespace app\controllers;

use Yii;
use DateTime;
use app\models\general\OrderOperation;
use app\models\general\OrderOperationSearch;
use app\models\general\Order;
use app\models\dict\Operation;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * OrderOperationController implements the CRUD actions for OrderOperation model.
 */
class OrderOperationController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all OrderOperation models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new OrderOperationSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single OrderOperation model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new OrderOperation model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new OrderOperation();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->order_operation_id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing OrderOperation model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post())) {
            $data = OrderOperation::find()->where(['order_operation_id' => $model->order_operation_id])->one();
            $post = Yii::$app->request->post();
       


            if($post['OrderOperation']['user_id'])
            {
                $data->user_id = $post['OrderOperation']['user_id'];
            }
            if($post['OrderOperation']['user_id_2'])
            {
                $data->user_id_2 = $post['OrderOperation']['user_id_2'];
            }


            if($model->date == '0000-00-00 00:00:00' || ( $post['OrderOperation']['user_id'] || $post['OrderOperation']['user_id_2'] ) )
            {
                $curent_date = new DateTime();
                $curent_date->modify('+1 hour');
                if($model->date != '0000-00-00 00:00:00')
                {
                    $data->date = $post['OrderOperation']['date'];
                } else
                {
                    $data->date = $curent_date->format('Y-m-d H:i:s'); 
                }
                

            } else
            {
                $data->user_id = 0;
                $data->user_id_2 = 0;
                $data->date = '0000-00-00 00:00:00';
            }

            $data->save();

            $order_operations_all = OrderOperation::find()->where(['order_id' => $model->order_id])->asArray()->all();
            $order_operations_complete = OrderOperation::find()->where(['order_id' => $model->order_id])->andWhere(['not', ['user_id' => '0']])->asArray()->all();

            $order_status = Order::find()->where(['order_id' => $model->order_id])->one();


            $loading_operations = Operation::find()->where(['like','name','Погрузочные работы'])->asArray()->all();
           	$loading_operations_id = '';

            foreach ($loading_operations as $lo) {
            	$loading_operations_id .= $lo['operation_id'].',';      	
            }
            $loading_operations_id = substr($loading_operations_id, 0,-1);
           


            $order_not_loading_operation_all = OrderOperation::find()->where(['order_id' => $model->order_id])->andWhere(['not in','operation_id',$loading_operations_id])->asArray()->all();
            $order_not_loading_operation_complete = OrderOperation::find()->where(['order_id' => $model->order_id])->andWhere(['not in','operation_id',$loading_operations_id])->andWhere(['not', ['user_id' => '0']])->asArray()->all();

            

           


            if( count($order_not_loading_operation_all) ==  count($order_not_loading_operation_complete))
            {
            	$order_status->status = '1';
            } else {

            	$order_status->status = '0';
            }


            if ( count($order_operations_all) == count($order_operations_complete) )
            {
            	$order_status->status = '2';
            }


            $order_status->save();


            
            
            return $this->redirect(['order/'.$model->order_id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing OrderOperation model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the OrderOperation model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return OrderOperation the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = OrderOperation::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

views/order-operation/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use app\models\dict\MaterialType;
use app\models\dict\Operation;
use app\models\general\Order;
use app\models\User;
use yii\helpers\ArrayHelper;

/* @var $this yii\web\View */
/* @var $model app\models\general\OrderOperation */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="order-operation-form">

    <?php $form = ActiveForm::begin();

    $params = [
        'prompt' => '-'
    ];

    

    $users = User::find()->all();
    //print_r($users);
    foreach ($users as $user) {
        $user['firstname'] = $user['lastname'].' '.$user['firstname'].' '.$user['patronymic'];
    }
    $items = ArrayHelper::map($users,'user_id','firstname');
    echo $form->field($model, 'user_id')->dropDownList($items,$params); 
    echo $form->field($model, 'user_id_2')->dropDownList($items,$params);
    if($model->date != '0000-00-00 00:00:00') {
    echo $form->field($model, 'date')->textInput(); 
    }
    
    ?>

   

    <div class="form-group">
        <?= Html::submitButton('Сохранить', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/order-operation/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\general\OrderOperationSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="order-operation-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'order_operation_id') ?>

    <?= $form->field($model, 'material_type_id') ?>

    <?= $form->field($model, 'operation_id') ?>

    <?= $form->field($model, 'order_id') ?>

    <?= $form->field($model, 'cost') ?>

    <?php // echo $form->field($model, 'user_id') ?>

    <?php // echo $form->field($model, 'date') ?>

    <?php // echo $form->field($model, 'description') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/order-operation/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\general\OrderOperation */

$this->title = 'Create Order Operation';
$this->params['breadcrumbs'][] = ['label' => 'Order Operations', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="order-operation-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/order-operation/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\general\OrderOperationSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Order Operations';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="order-operation-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a('Create Order Operation', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'order_operation_id',
            'material_type_id',
            'operation_id',
            'order_id',
            'cost',
            //'user_id',
            //'date',
            //'description',

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>
</div>

views/order-operation/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\general\OrderOperation */
use app\models\general\Order;
$order_name = Order::find()->where(['order_id' => $model->order_id])->asArray()->one();

$this->params['breadcrumbs'][] = ['label' => 'Заказы', 'url' => ['order/index']];
$this->params['breadcrumbs'][] = ['label' => $order_name['order_general_id'], 'url' => ['order/'.$model->order_id]];
$this->params['breadcrumbs'][] = 'Изменить операцию';
?>
<div class="order-operation-update">

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/order-operation/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\general\OrderOperation */

$this->title = $model->order_operation_id;
$this->params['breadcrumbs'][] = ['label' => 'Order Operations', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="order-operation-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->order_operation_id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->order_operation_id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'order_operation_id',
            'material_type_id',
            'operation_id',
            'order_id',
            'cost',
            'user_id',
            'user_id_2',
            'date',
            'description',
        ],
    ]) ?>

</div>